export const FETCH_HISTORY_DATA_REQUEST = "FETCH_HISTORY_DATA_REQUEST"
export const FETCH_HISTORY_DATA_SUCCESS = "FETCH_HISTORY_DATA_SUCCESS"
export const FETCH_HISTORY_DATA_ERROR = "FETCH_HISTORY_DATA_ERROR"