export const FETCH_HISTORY_DATA_REQUEST = "FETCH_HISTORY_DATA_REQUEST"
export const FETCH_HISTORY_DATA_SUCCESS = "FETCH_HISTORY_DATA_SUCCESS"
export const FETCH_HISTORY_DATA_ERROR = "FETCH_HISTORY_DATA_ERROR"

export const GET_TWENTY_FOUR_HOURS_DATA = "GET_TWENTY_FOUR_HOURS_DATA"
export const GET_ONE_WEEK_DATA = "GET_ONE_WEEK_DATA"
export const GET_ONE_MONTH_DATA = "GET_ONE_MONTH_DATA"

export const FETCH_NEWS_DATA_REQUEST = "FETCH_NEWS_DATA_REQUEST"
export const FETCH_NEWS_DATA_SUCCESS = "FETCH_NEWS_DATA_SUCCESS"
export const FETCH_NEWS_DATA_ERROR = "FETCH_NEWS_DATA_ERROR"

