const env = process.env

export const BCX_BASE_URL = env.REACT_APP_BASE_BCX_URL
export const BCX_HISTORIC_VALUE_API_PATH = env.REACT_APP_BCX_HISTORIC_VALUE_API_PATH
export const BCX_CURRENT_PRICE_API_PATH = env.REACT_APP_BCX_CURRENT_PRICE_API_PATH
export const NEWS_API_URL = env.REACT_APP_NEWS_API_URL